package ourLib.dbUtils;

import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.sql.SQLException;


public interface HasAutogeneratedKey {
	default public void SetAutogeneratedKey(ResultSet rs) throws SQLException {
		for(Field f : this.getClass().getDeclaredFields()) {
			if(f.isAnnotationPresent(AutoGenerated.class)) {
				try {
					Integer key = rs.getInt(1);
					f.setAccessible(true);
					f.set(this, key);
					f.setAccessible(false);
					return;
				} catch (IllegalArgumentException | IllegalAccessException e) {
					throw new SQLException("NO se pudo mapear la clave autogenerada");
				}
			}
		}
	}
}
