package ourLib.dbUtils;

import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.sql.SQLException;

import ourLib.AppException;


public interface HasAutogeneratedKey {
	default public void SetAutogeneratedKey(ResultSet rs) throws AppException {
		for(Field f : this.getClass().getDeclaredFields()) {
			if(f.isAnnotationPresent(AutoGenerated.class)) {
				try {
					Integer key = rs.getInt(1);
					f.setAccessible(true);
					f.set(this, key);
					f.setAccessible(false);
					return;
				} catch (IllegalArgumentException | IllegalAccessException | SQLException e) {
					throw new AppException("NO se pudo mapear la clave autogenerada", 500);
				}
			}
		}
		throw new AppException("NO se encontro atributo con @AutoGenerated en la clase "+this.getClass().getName(), 500);
		
		
	}
}
