package data;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import dbUtils.Dao;
import dbUtils.StatementWrapper;
import entities.Droga;

public class DrogasDao extends Dao<Droga> {

	public void add(Droga drug) {
	StatementWrapper sw = new StatementWrapper("insert into drogas (nombre) values (?)");
	sw.push(drug.getNombre());
	executeSimpleAdd(sw, drug);	
	}

	@Override
	protected Droga mapFromResulset(ResultSet rs) throws SQLException {
		Droga drug = new Droga();
		while(rs.next()) {
		drug.setCod(rs.getInt("codigo"));
		drug.setNombre(rs.getString("nombre"));
		}
		return drug;
	}

	@Override
	protected void mapAutogeneratedKey(Droga e, ResultSet rs) throws SQLException {
		while(rs.next()) {
			e.setCod(rs.getInt("codigo"));}		
	}

}
