package data;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import dbUtils.Dao;
import dbUtils.DbConnector;
import dbUtils.StatementWrapper;
import entities.Droga;

public class DrogasDao extends Dao<Droga> {

	public void add(Droga drug) {
		PreparedStatement pstmt=null;
		ResultSet rs=null;
		
		try {
			pstmt = DbConnector.getInstancia().getConn().
					prepareStatement(
							"insert into drogas(nombre) values(?)",
							PreparedStatement.RETURN_GENERATED_KEYS
							);
			pstmt.setString(1, drug.getNombre());
			pstmt.executeUpdate();
			
			rs=pstmt.getGeneratedKeys();
            if(rs!=null && rs.next()){
                drug.setCod(rs.getInt(1));
                
                
            }	
               
		}  
		catch (SQLException e) { e.printStackTrace(); } 
		finally { closeResourses(pstmt, rs); }
	}

	@Override
	protected Droga mapFromResulset(ResultSet rs) throws SQLException {
		Droga drug = new Droga();
		drug.setCod(rs.getInt("codigo"));
		drug.setNombre(rs.getString("nombre"));
		return drug;
	}

	@Override
	protected void mapAutogeneratedKey(Droga e, ResultSet rs) throws SQLException {
			e.setCod(rs.getInt(1));
	}

}
