package data;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;


import dbUtils.Dao;
import dbUtils.DbConnector;
import dbUtils.StatementWrapper;
import entities.Droga;

public class DrogasDao extends Dao<Droga> {

	public LinkedList<Droga> getAll() throws SQLException{
		return executeFindAll(new StatementWrapper("select * from drogas"));
	}
	
	public void add(Droga drug) throws SQLException {
		StatementWrapper stw= new StatementWrapper("insert into drogas(nombre) values(?)");
		stw.push(drug.getNombre());
		executeAddWithGeneratedKeys(stw, drug);
	}

	public void update(Droga drug) throws SQLException {
		PreparedStatement pstm =null;	
		try {
			pstm= DbConnector.getInstancia().getConn()
					.prepareStatement("update drogas set nombre=? where codigo=?");
			pstm.setString(1,drug.getNombre());
			pstm.setInt(2,drug.getCod());
			pstm.execute();
			
		} catch (SQLException e) {
			e.printStackTrace();
			throw e;   
		} finally {
			closeResourses(pstm);
		}
	}
	
	public void delete(Droga drug) throws SQLException{
		PreparedStatement pstm =null;
		try {
			pstm= DbConnector.getInstancia().getConn()
					.prepareStatement("delete from drogas where codigo=?");
			pstm.setInt(1,drug.getCod());
			pstm.execute();
			//ver como habria que tratar el tema de este tipo de borrado (en cascada o que)
			
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			closeResourses(pstm);
		}
	}
		
	@Override
	protected Droga mapFromResulset(ResultSet rs) throws SQLException {
		Droga drug = new Droga();
		drug.setCod(rs.getInt("codigo"));
		drug.setNombre(rs.getString("nombre"));
		return drug;
	}

	@Override
	protected void mapAutogeneratedKey(Droga e, ResultSet rs) throws SQLException {
			e.setCod(rs.getInt(1));
	}

}
