package data;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;

import dbUtils.Dao;
import dbUtils.StatementWrapper;
import entities.ObraSocial;

public class ObrasSocialesDao extends Dao<ObraSocial>{

	@Override
	protected ObraSocial mapFromResulset(ResultSet rs) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected void mapAutogeneratedKey(ObraSocial os, ResultSet rs) throws SQLException {
		os.setId(rs.getInt(1));
	}

	@Override
	public ObraSocial getOne(ObraSocial p) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public LinkedList<ObraSocial> getAll() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void add(ObraSocial os) throws SQLException {
		StatementWrapper stw=new StatementWrapper("insert into obras_sociales (nombre,telefono,email,descuentoGeneral) values (?,?,?,?)");
		stw.push(os.getNombre())
			.push(os.getTelefono())
			.push(os.getEmail())
			.push(os.getDescuento());
		executeAddWithGeneratedKeys(stw, os);
	}

	@Override
	public void update(ObraSocial p) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete(ObraSocial p) throws SQLException {
		// TODO Auto-generated method stub
		
	}

}
