package data;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;

import entities.Usuario;
import ourLib.dbUtils.Dao;

public class UsuariosDao extends Dao<Usuario>{

	@Override
	protected Usuario mapFromResulset(ResultSet rs) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected void mapAutogeneratedKey(Usuario e, ResultSet rs) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Usuario getOne(Usuario p) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public LinkedList<Usuario> getAll() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void add(Usuario p) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void update(Usuario p) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete(Usuario p) throws SQLException {
		// TODO Auto-generated method stub
		
	}

}
