package dbUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.LinkedList;



@FunctionalInterface
interface ParamterAdder{
	public void apply(Integer index,PreparedStatement st ) throws SQLException;
}

public class StatementWrapper {
		private String query;
		private LinkedList<ParamterAdder> paramterAdders;
		int autoGeneratedKey;

		public StatementWrapper(String _query, int _autoGeneratedKey) {
			query=_query;
			paramterAdders= new LinkedList<ParamterAdder>();
			autoGeneratedKey=_autoGeneratedKey;
		}

		public StatementWrapper(String _query) {
			new StatementWrapper(_query, PreparedStatement.NO_GENERATED_KEYS);
		}
		
		
		public PreparedStatement makeStatement(Connection con) throws SQLException {
			PreparedStatement st= con.prepareStatement(query, autoGeneratedKey);
			int index=1;
			for(ParamterAdder lambda: paramterAdders) {
				lambda.apply(index, st);
				index++;
			}
			return st;
		}

		
		public StatementWrapper push(String s) {
			paramterAdders.add((index, st)->{
				try { st.setString(index, s); } 
				catch (SQLException e) { throw e; }
			});
			return this;
		}
		
		public StatementWrapper push(Integer i) {
			paramterAdders.add((index, st)->{
				try { st.setInt(index, i); } 
				catch (SQLException e) { throw e; }
			});
			return this;
		}
		

		public StatementWrapper push(Boolean b) {
			paramterAdders.add((index, st)->{
				try { st.setBoolean(index, b); } 
				catch (SQLException e) { throw e; }
			});
			return this;
		}
		
		
		
		
}
		
		
		
	

