package entities;

import ourLib.Parsers.JsonMaker;
import ourLib.Parsers.Jsonable;
import ourLib.dbUtils.AutoGenerated;
import ourLib.dbUtils.HasAutogeneratedKey;

public class Laboratorio implements HasAutogeneratedKey, Jsonable{
	
	@AutoGenerated
	private Integer codigo;
	private String nombre;
	private String telefono;
	private String email;
	
	public Integer getCodigo() {
		return codigo;
	}
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getTelefono() {
		return telefono;
	}
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@Override
	public String toJson() {
		JsonMaker jm= new JsonMaker();
		jm.set("cod_lab", codigo);
		jm.set("name_lab", nombre);
		jm.set("telefono_lab", telefono);
		jm.set("email_lab", email);
		return jm.getJSONObject();
	}
}
