package entities;

import java.util.HashMap;

import ourLib.dbUtils.AutoGenerated;
import ourLib.dbUtils.HasAutogeneratedKey;

public class Medicamento implements HasAutogeneratedKey {

	@AutoGenerated
	private Integer codigoBarra; //WAT???????????????????
	private Laboratorio laboratorio;
	private String nombre;
	private Double size;
	private String unidad;
	private Double precio;
	private HashMap<Integer, Dosis> dosis;
	
	public Medicamento() {
		dosis=new HashMap<>();
	}
	public Integer getCodigoBarra() {
		return codigoBarra;
	}
	public void setCodigoBarra(Integer codigoBarra) {
		this.codigoBarra = codigoBarra;
	}
	public Laboratorio getLaboratorio() {
		return laboratorio;
	}
	public void setLaboratorio(Laboratorio laboratorio) {
		this.laboratorio = laboratorio;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public Double getSize() {
		return size;
	}
	public void setSize(Double size) {
		this.size = size;
	}
	public Double getPrecio() {
		return precio;
	}
	public void setPrecio(Double precio) {
		this.precio = precio;
	}
	public String getUnidad() {
		return unidad;
	}
	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}
	
	public void addDosis(Dosis dosisToBeAdded) {
		dosis.put(dosisToBeAdded.getCodigoDroga(), dosisToBeAdded);
	}
	public void addAllDosis(HashMap<Integer, Dosis> dosisToBeAdded) {
		this.dosis=dosisToBeAdded;
	}	
	public void removeDosis(Dosis dosisToBeRemoved) {
		this.dosis.remove(dosisToBeRemoved.getCodigoDroga());
	}	
	public boolean hasDosis(Dosis dosisToCheck) {
		return this.dosis.containsKey(dosisToCheck.getCodigoDroga());
	}	
	public HashMap<Integer, Dosis> getAllDosis(){
		return this.dosis;
	}

	
	
	
	
}
